language: python
sudo: false
install:
  - pip install --upgrade pip
  - pip install -r requirements/development.txt
  - pip install coveralls
script:
  - coverage run --source='fossevents' --omit='*tests*,*requirements*,*commands*,*migrations*,*admin*,*wsgi*' -m py.test -v --tb=native

before_script:
- flake8
- export DATABASE_URL=postgres://postgres@localhost/fossevents
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c "CREATE DATABASE fossevents;" -U postgres

# report coverage to coveralls.io
after_success: coveralls

deploy:
  provider: heroku
  buildpack: python
  strategy: api
  api_key:
    secure: ifPDQ9zzJ9rrpiIubGlv53GCC4o+75j3WJX8A4vtdNcUtkuG26/xmoMKKC2yXa9EnRCzXe2oFAtNxXso1OqjWarfErzNQLHFVpy2mA0wpYTjPx026VPcFI/qH0PgMQzQySvaRfrrM2yLshrA4QFEoxhIxGZaNMwQe2rrFN8GZDQ=
  app:
    master: fossevents
  on:
    repo: fossevents/fossevents.in
  run:
    - "python manage.py migrate"

